INSERT OR IGNORE INTO posts (id, bbsid, board_id, user_id, title, content, content_text, signature, posted_at, reply_count, source_file, wayback_ts) VALUES (187, 136970, 11, 48, 'About Designing Vote of TOP15', 'The present voting mechanism, similar as many others in this disappointing world, could be thought as a compromise between the ideality and the reality. Theoretically, the most efficient voting mechanism should be the one that each virtual member of Cafewoo, represented by a single ID, votes for his or her 15 favorite articles after a careful review of all the articles in all the 9 sectors. However, to implement such a mechanism in reality, we have to consider the constraints of both the individual rationality and the incentive compatibility. 
<br>
<br>First, it will be implausible to assume that each member will be that patient and devoted to review all the articles in all the sectors of the past whole one year, since even those most zealous fans, such as I myself, will be exhausted or, even worse, daunted by doing that. To reduce such inefficiency, we design to ask each sector master to select five articles as candidates before the vote starts. It could be argued such a device is not flawless at all, however, from another aspect, the inefficiency caused by the selection of the sector masters, if it is significant enough to be criticized, will be far less than that caused by the mechanism of putting bulbs in the articles favored by those masters. Whereas it seems the latter device has been proved as a widely accepted and probably the most appealing mechanism in Cafewoo during the last two years. 
<br>
<br>Second, it has been evidenced that a large proportion of members in Cafewoo have registered more than one ID. Hence another important factor we have to consider is that, in the absence of appropriate constraint, it will be no bad for those members with two or more IDs to vote for more than one time, thus considerably reducing the plausibility of the final result. This is why we restrict the electorate to those who had registered before the announcement of the vote and had posted or replied to articles. Yet I will be grateful if any better alternatives are proposed, since they are really beyond my intelligence.
<br>
<br>Nevertheless, I am not intended here to declaim any vindications for the voting mechanism, since that is not my purpose at all. All I hope, as most of you, is simply to make this cozy Cafewoo a better place with more participations from all the fans. And I will be very happy if the vote can contribute even a little bit to this.
<br>
<br>Merry Christmas and Happy New Year!', 'The present voting mechanism, similar as many others in this disappointing world, could be thought as a compromise between the ideality and the reality. Theoretically, the most efficient voting mechanism should be the one that each virtual member of Cafewoo, represented by a single ID, votes for his or her 15 favorite articles after a careful review of all the articles in all the 9 sectors. However, to implement such a mechanism in reality, we have to consider the constraints of both the individual rationality and the incentive compatibility.

First, it will be implausible to assume that each member will be that patient and devoted to review all the articles in all the sectors of the past whole one year, since even those most zealous fans, such as I myself, will be exhausted or, even worse, daunted by doing that. To reduce such inefficiency, we design to ask each sector master to select five articles as candidates before the vote starts. It could be argued such a device is not flawless at all, however, from another aspect, the inefficiency caused by the selection of the sector masters, if it is significant enough to be criticized, will be far less than that caused by the mechanism of putting bulbs in the articles favored by those masters. Whereas it seems the latter device has been proved as a widely accepted and probably the most appealing mechanism in Cafewoo during the last two years.

Second, it has been evidenced that a large proportion of members in Cafewoo have registered more than one ID. Hence another important factor we have to consider is that, in the absence of appropriate constraint, it will be no bad for those members with two or more IDs to vote for more than one time, thus considerably reducing the plausibility of the final result. This is why we restrict the electorate to those who had registered before the announcement of the vote and had posted or replied to articles. Yet I will be grateful if any better alternatives are proposed, since they are really beyond my intelligence.

Nevertheless, I am not intended here to declaim any vindications for the voting mechanism, since that is not my purpose at all. All I hope, as most of you, is simply to make this cozy Cafewoo a better place with more participations from all the fans. And I will be very happy if the vote can contribute even a little bit to this.

Merry Christmas and Happy New Year!', NULL, '2001-12-13 21:10:00', 3, '20020112075702_bbsid_136970_board_11_c0d8fe8d2f.html', '20020112075702');
