INSERT OR IGNORE INTO posts (id, bbsid, board_id, user_id, title, content, content_text, signature, posted_at, reply_count, source_file, wayback_ts) VALUES (1412, 193129, 2, 870, '[转贴]LOVE', 'It all started when I was 16 years old.While I was playing outside on my farm in California,I met a boy.He was an average kind of boy who teased you and then you chased them and beat them up.After that first meeting in which I beat him up we kept on meeting and beating each other up at the fence.That only lasted for a little while though.We would meet at the fence all the time and we were always
<br>together.I would tell him all my secrets.He was very quiet,he would just listen to what I had to say.I found him easy to talk to and I could talk to him about everything.In school we had separate friends but when we got home we would always talk about what happened in school.
<br>
<br>One day I said to him that a guy I liked hurt me and broke my heart.He just comforted me and said everything would be okay.He gave me words of encouragement and helped me get over him.I was happy and thought of him as a real friend.But I knew that there was something else about him that I liked. I thought of it that night and figured it was just a friend kinda thing that I was feeling.All through
<br>high school and even through graduation we were always together and of course I thought of it as being friends.But I knew deep inside that I really felt differently.
<br>
<br>On graduation night even though we had different dates to the prom I wanted to be with him.That night after everybody went home I went to his house and wanted to tell him that I wanted to see him.Well, that night was my big chance and all I did was just sit there with him watching the stars and talking about what I was going to do and what he was going to do.I looked into his eyes and listened to him talk
<br>about what his dream was.How he wanted to get married and settle down! He said how he wanted to be rich and successful.All I could do was to tell him my dream and cuddle next to him.I went home hurting because I didn''t tell him how I was feeling. I wanted to tell him so bad that I loved him but I was too scared and frightened.I let my feelings go and told myself that someday I would tell him just how I felt. 
<br>
<br>All through college I wanted to tell him but he always had someone with him.After graduation he got a job in New York.I was happy for him but at the same time I was sad to see him go.I was sad also because I didn''t tell him how I felt.But I couldn''t let him know now that he was leaving for his big job.So I just kept it to myself and watched him get on the plane.I cried as I hugged him for what I felt was going to be the last time.I went home that night and cried my eyes out.I felt hurt that I didn''t tell him what I had inside my heart.
<br>
<br>Well, I got a job as a secretary and then worked my way to a computer analyst.I was proud of what I had accomplished.One day I got a letter with an invitation to a wedding.It was from him! I was happy and sad at the same time.Now I know that I could never be with him and that we could only be friends.I went to the wedding the next month.It was a big occasion.It was a big church wedding with the reception at a hotel.I met the bride and of course I talked to him too.I fell in love one more time.But I held back so it wouldn''t spoil what should be the happiest day in his life.I tried to have fun that night but it was killing me inside watching him being so happy and me trying to be happy covering up my sadness tears inside of me. 
<br>
<br>I left New York feeling that I did the right thing.Before I left on the flight,he came running out of nowhere and said his good-byes and how he was very happy to see me.I came home and just tried to forget about what went on in New York.I had to go on with my life.As the years went on,we wrote to each other on what was going on and how he had missed talking to me.On one occasion he never wrote back to me at all.I was getting worried as to why he hadn''t written anything for a long time after I had already written 6 letters to him.Well,just when everything seemed hopeless and sad in my life,I got a note that said: &quot;Meet me at the fence where we used to talk about things&quot;.I went and saw him there.I was happy to see him,but he was broken-hearted and sad inside.We hugged until we couldn''t breathe anymore.Then he told me about the divorce and why he hadn''t written for a long time.He cried until he couldn''t cry anymore.Finally, we went back to the house and talked and laughed about what I had been going and to catch up on old times.But in all of this,I couldn''t tell him how I felt about him.
<br>
<br>In the days that followed,he had fun and forgot about all his problem and his divorce.I fell in love again with him.When it came time for him to leave back to New York,I went to see him off and cried.I hated to see him leave.He promised to see me every time he could get a vacation.I couldn''t wait for him to come so I could be with him.We would always have fun when we were together.
<br>
<br>One day he didn''t show up like he said he would.I figured that he might have been busy.The days turned into months and I just forgot about it.Then I got a call one day from a lawyer in New York.The lawyer said that he had died in a car accident going to the airpor,and that it took this long till everything was settled.It broke my heart.I was shocked about what took place.Now I knew why he didn''t come that day.Again,I was broken-hearted.I cried that night,cried tears of sadness and heartache.I asked questions: &quot;Why did this happen to a kind guy like him?&quot;
<br>
<br>I gathered my things and went to New York for the reading of his will.Of course,things were given to his family and his ex-wife.I finally got to meet her since the last time we met at the wedding.She explained to me how he was and how he always provided.But he was always unhappy.She would always try everything but she couldn''t get him happy,as he was that night at their wedding.When the will was read,the one thing that was given to me was a diary.It was a dairy that of his life.I cried as it was given to me.I didn''t know what to think.Why was this given to me?I took it and flew back to California.As I flew on the plane I remembered the good times that we had together.I started reading the diary and what was written.The diary was started with the day we first met.I read on till I started to cry.The diary told of him saying that he had fallen in love with me that day I was broken-hearted.But he was too afraid to tell me what he had felt.That is why he was so quiet and liked to listen to me.It told of how he wanted to tell me so many times,but was too afraid to say anything.It told of when he went to New York and fell in love with another.How the happiest time he had was seeing me and dancing with me at the wedding! He said he imagined it was our wedding.How he was always unhappy till he had no choice but to divorce his wife.How the best time in his life was to read the letters written to him by me.Finally,the diary ended when it said,&quot;today I will tell her I love her&quot;.It was the day he was killed! The day I was going to finally find out what was really in his heart! 
<br>
<br>So if you love someone,don''t wait till tomorrow to tell him/her.Maybe the next day will never come
<br>at
<br>all. 
<br>
<br>
<br>Thanks for reading.', 'It all started when I was 16 years old.While I was playing outside on my farm in California,I met a boy.He was an average kind of boy who teased you and then you chased them and beat them up.After that first meeting in which I beat him up we kept on meeting and beating each other up at the fence.That only lasted for a little while though.We would meet at the fence all the time and we were always

together.I would tell him all my secrets.He was very quiet,he would just listen to what I had to say.I found him easy to talk to and I could talk to him about everything.In school we had separate friends but when we got home we would always talk about what happened in school.

One day I said to him that a guy I liked hurt me and broke my heart.He just comforted me and said everything would be okay.He gave me words of encouragement and helped me get over him.I was happy and thought of him as a real friend.But I knew that there was something else about him that I liked. I thought of it that night and figured it was just a friend kinda thing that I was feeling.All through

high school and even through graduation we were always together and of course I thought of it as being friends.But I knew deep inside that I really felt differently.

On graduation night even though we had different dates to the prom I wanted to be with him.That night after everybody went home I went to his house and wanted to tell him that I wanted to see him.Well, that night was my big chance and all I did was just sit there with him watching the stars and talking about what I was going to do and what he was going to do.I looked into his eyes and listened to him talk

about what his dream was.How he wanted to get married and settle down! He said how he wanted to be rich and successful.All I could do was to tell him my dream and cuddle next to him.I went home hurting because I didn''t tell him how I was feeling. I wanted to tell him so bad that I loved him but I was too scared and frightened.I let my feelings go and told myself that someday I would tell him just how I felt.

All through college I wanted to tell him but he always had someone with him.After graduation he got a job in New York.I was happy for him but at the same time I was sad to see him go.I was sad also because I didn''t tell him how I felt.But I couldn''t let him know now that he was leaving for his big job.So I just kept it to myself and watched him get on the plane.I cried as I hugged him for what I felt was going to be the last time.I went home that night and cried my eyes out.I felt hurt that I didn''t tell him what I had inside my heart.

Well, I got a job as a secretary and then worked my way to a computer analyst.I was proud of what I had accomplished.One day I got a letter with an invitation to a wedding.It was from him! I was happy and sad at the same time.Now I know that I could never be with him and that we could only be friends.I went to the wedding the next month.It was a big occasion.It was a big church wedding with the reception at a hotel.I met the bride and of course I talked to him too.I fell in love one more time.But I held back so it wouldn''t spoil what should be the happiest day in his life.I tried to have fun that night but it was killing me inside watching him being so happy and me trying to be happy covering up my sadness tears inside of me.

I left New York feeling that I did the right thing.Before I left on the flight,he came running out of nowhere and said his good-byes and how he was very happy to see me.I came home and just tried to forget about what went on in New York.I had to go on with my life.As the years went on,we wrote to each other on what was going on and how he had missed talking to me.On one occasion he never wrote back to me at all.I was getting worried as to why he hadn''t written anything for a long time after I had already written 6 letters to him.Well,just when everything seemed hopeless and sad in my life,I got a note that said: "Meet me at the fence where we used to talk about things".I went and saw him there.I was happy to see him,but he was broken-hearted and sad inside.We hugged until we couldn''t breathe anymore.Then he told me about the divorce and why he hadn''t written for a long time.He cried until he couldn''t cry anymore.Finally, we went back to the house and talked and laughed about what I had been going and to catch up on old times.But in all of this,I couldn''t tell him how I felt about him.

In the days that followed,he had fun and forgot about all his problem and his divorce.I fell in love again with him.When it came time for him to leave back to New York,I went to see him off and cried.I hated to see him leave.He promised to see me every time he could get a vacation.I couldn''t wait for him to come so I could be with him.We would always have fun when we were together.

One day he didn''t show up like he said he would.I figured that he might have been busy.The days turned into months and I just forgot about it.Then I got a call one day from a lawyer in New York.The lawyer said that he had died in a car accident going to the airpor,and that it took this long till everything was settled.It broke my heart.I was shocked about what took place.Now I knew why he didn''t come that day.Again,I was broken-hearted.I cried that night,cried tears of sadness and heartache.I asked questions: "Why did this happen to a kind guy like him?"

I gathered my things and went to New York for the reading of his will.Of course,things were given to his family and his ex-wife.I finally got to meet her since the last time we met at the wedding.She explained to me how he was and how he always provided.But he was always unhappy.She would always try everything but she couldn''t get him happy,as he was that night at their wedding.When the will was read,the one thing that was given to me was a diary.It was a dairy that of his life.I cried as it was given to me.I didn''t know what to think.Why was this given to me?I took it and flew back to California.As I flew on the plane I remembered the good times that we had together.I started reading the diary and what was written.The diary was started with the day we first met.I read on till I started to cry.The diary told of him saying that he had fallen in love with me that day I was broken-hearted.But he was too afraid to tell me what he had felt.That is why he was so quiet and liked to listen to me.It told of how he wanted to tell me so many times,but was too afraid to say anything.It told of when he went to New York and fell in love with another.How the happiest time he had was seeing me and dancing with me at the wedding! He said he imagined it was our wedding.How he was always unhappy till he had no choice but to divorce his wife.How the best time in his life was to read the letters written to him by me.Finally,the diary ended when it said,"today I will tell her I love her".It was the day he was killed! The day I was going to finally find out what was really in his heart!

So if you love someone,don''t wait till tomorrow to tell him/her.Maybe the next day will never come

at

all.

Thanks for reading.', 'If there is light in the soul,

there will be beauty in the person.

If there is beauty in the person,

there will be harmony in the house.

If there is harmony in the house,

there will be order in the nation.

If there is order in the nation,

there will be peace in the world.', '2003-01-12 00:28:00', 4, '20030217222517_bbsid_193129_board_2_fc285cc736.html', '20030217222517');
